ffmpeg
    -y
    -i "battleful-days.mp3"
    -c:a aac
    -b:a 128k
    -muxdelay 0
    -f segment
    -sc_threshold 0
    -segment_time 1
    -segment_list "playlist.m3u8"
    -segment_format mpegts "file%05d.m4a"
